### ISSUE TITLE
Feature request: set subscription period, expiration cancellation reminder to unsubscribe

### ISSUE THREAD

**Issue by lin1123** [ellite/Wallos#293] opened 2024-05-01 00:27 UTC
thanks
Please add teletram bot Reminder function

**Comment by fin444** [comment] 2024-05-04 20:52
duplicate of https://github.com/ellite/Wallos/issues/257

**Comment by b1nary-b0b** [comment] 2024-06-29 11:34
> duplicate of #257

As far as I understand, this is more about subscription management, i.e. subscription date, setting a date period before expiration to get reminded and so on. I would also love to have this! I always forget to cancel on time because every subscription provider has slightly different deadlines before expiration for cancelation.

**Comment by ellite** [comment] 2024-06-29 11:53
Yes, this is not a duplicate.
I still don't have a plan to implement this. But I'll get to it eventually.

**Comment by ellite** [comment] 2024-07-05 17:29
Cancelation reminders implemented.
Regards.

**Closed by ellite** 2024-07-05 17:29 UTC
Labels: enhancement
